# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i60M3DPlVYRVfSITUbEslt0hS5k1-TGP
"""

UID = 118552804
Last_Name= 'Murali'
First_Name = 'Neharidha'

def caesar_str_enc(plaintext, k):
    txt=plaintext.replace(" ","")
    text=txt.upper()
    ciphertext = ''
    if k>26:
      k=k%26
    else:
      k=k
    for char in text:
        if char.isalpha():
            new_char_code = ord(char) + k
            if new_char_code>ord('Z'):
                new_char_code-=26
            elif new_char_code<ord('A'):
                new_char_code+=26
            ciphertext += chr(new_char_code)
    return ciphertext

def caesar_str_dec(ciphertext, k):
    txt=ciphertext.replace(" ","")
    text=txt.upper()
    plaintext = ''
    if k>26:
      k=k%26
    else:
      k=k
    for char in text:
        if char.isalpha():
            new_char_code = ord(char) - k
            if new_char_code>ord('Z'):
                new_char_code-=26
            elif new_char_code<ord('A'):
                new_char_code+=26
            plaintext += chr(new_char_code)
    return plaintext

def test_function():
  t="HELLO"
  k=3
  enc=caesar_str_enc(t,k)
  dec=caesar_str_dec(enc,k)
  assert t==dec, "error_stt"

  t="HELLO"
  k=2
  enc=caesar_str_enc(t,k)
  dec=caesar_str_dec(enc,k)
  assert t==dec, "error_stt"
  return None


  
if __name__ == "__main__":
    input_str = 'a test sentence'
    k = 2
    encstr = caesar_str_enc(input_str, k)
    print(encstr)
    decstr = caesar_str_dec(encstr, k)
    print(decstr)
    test_function()